spring:
  datasource:
    username: root
    password: 123456
    # 注意时间区
    url: jdbc:mysql://localhost:3306/mybatis?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
    driver-class-name: com.mysql.jdbc.Driver # mysql 5
    type: com.alibaba.druid.pool.DruidDataSource
    dbcp2:
      initial-size: 5
    tomcat:
      max-active: 200

    filters: stat,wall,log4j


